name: Test Nipe on Fedora
on: [push]

jobs:
  build:
    runs-on: fedora-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo dnf install -y perl cpanminus gcc make zlib-devel
        sudo cpanm --installdeps .
        sudo perl nipe.pl install
    - name: Verify Nipe status
      run: |
        sudo perl nipe.pl status
